# Generated by Django 6.0.6 on 2026-09-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMenu',
            fields=[
                ('menu_id', models.AutoField(db_column='MenuId', primary_key=True, serialize=False)),
                ('menu_name', models.CharField(db_column='MenuName', max_length=255)),
                ('url_page', models.CharField(db_column='UrlPage', max_length=255)),
                ('view_access', models.BooleanField(db_column='ViewAccess', default=False)),
                ('add_access', models.BooleanField(db_column='AddAccess', default=False)),
                ('edit_access', models.BooleanField(db_column='EditAccess', default=False)),
                ('delete_access', models.BooleanField(db_column='DeleteAccess', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'MasterMenu',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleId', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='RoleName', max_length=255)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('role_group_id', models.AutoField(db_column='RoleGroupId', primary_key=True, serialize=False)),
                ('role_group_name', models.CharField(db_column='RoleGroupName', max_length=255)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'RoleGroup',
            },
        ),
        migrations.CreateModel(
            name='MasterSubMenu',
            fields=[
                ('sub_menu_id', models.AutoField(db_column='SubMenuId', primary_key=True, serialize=False)),
                ('menu_name', models.CharField(db_column='MenuName', max_length=255)),
                ('url_page', models.CharField(db_column='UrlPage', max_length=255)),
                ('view_access', models.BooleanField(db_column='ViewAccess', default=False)),
                ('add_access', models.BooleanField(db_column='AddAccess', default=False)),
                ('edit_access', models.BooleanField(db_column='EditAccess', default=False)),
                ('delete_access', models.BooleanField(db_column='DeleteAccess', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('menu', models.ForeignKey(db_column='MenuId', on_delete=django.db.models.deletion.CASCADE, to='users.mastermenu')),
            ],
            options={
                'db_table': 'MasterSubMenu',
            },
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('role_access_id', models.AutoField(db_column='RoleAccessId', primary_key=True, serialize=False)),
                ('view_access', models.BooleanField(db_column='ViewAccess', default=False)),
                ('add_access', models.BooleanField(db_column='AddAccess', default=False)),
                ('edit_access', models.BooleanField(db_column='EditAccess', default=False)),
                ('delete_access', models.BooleanField(db_column='DeleteAccess', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('menu', models.ForeignKey(db_column='MenuId', on_delete=django.db.models.deletion.CASCADE, to='users.mastermenu')),
                ('role', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'db_table': 'RoleAccess',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='role_group',
            field=models.ForeignKey(db_column='RoleGroupId', on_delete=django.db.models.deletion.CASCADE, to='users.rolegroup'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='Firstname', max_length=255)),
                ('last_name', models.CharField(db_column='Lastname', max_length=255)),
                ('display_name', models.CharField(db_column='Displayname', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('phone', models.CharField(db_column='Phone', max_length=50)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('salt_key', models.CharField(blank=True, db_column='SaltKey', max_length=255, null=True)),
                ('is_changed', models.BooleanField(db_column='IsChanged', default=False)),
                ('password_change_date', models.DateTimeField(blank=True, db_column='PasswordChangeDate', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('last_date', models.DateTimeField(auto_now=True, db_column='LastDate')),
                ('last_changed_by', models.IntegerField(blank=True, db_column='LastChangedBy', null=True)),
                ('role', models.ForeignKey(db_column='RoleId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user_address_id', models.AutoField(db_column='UserAddressId', primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(db_column='AddressLine1', max_length=1000)),
                ('address_line_2', models.CharField(blank=True, db_column='AddressLine2', max_length=1000, null=True)),
                ('city', models.CharField(db_column='City', max_length=255)),
                ('state', models.CharField(db_column='State', max_length=255)),
                ('country', models.IntegerField(db_column='Country')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('last_date', models.DateTimeField(auto_now=True, db_column='LastDate')),
                ('last_changed_by', models.IntegerField(blank=True, db_column='LastChangedBy', null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserAddress',
            },
        ),
        migrations.CreateModel(
            name='UserLoginDetails',
            fields=[
                ('user_login_details_id', models.AutoField(db_column='UserLoginDetails', primary_key=True, serialize=False)),
                ('login_date', models.DateTimeField(auto_now_add=True, db_column='LoginDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserLoginDetails',
            },
        ),
    ]
