# Generated by Django 6.0.6 on 2026-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_days',
            field=models.CharField(blank=True, db_column='PreferredDays', max_length=255, null=True),
        ),
    ]
