# Generated by Django 6.0.6 on 2026-10-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userexperience_userqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.user')),
            ],
            options={
                'db_table': 'UserCertification',
            },
        ),
    ]
