# Generated by Django 6.0.6 on 2026-10-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usercertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, db_column='DOB', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, db_column='Gender', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, db_column='ParentName', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, db_column='ParentPhone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, db_column='UserCode', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_days',
            field=models.CharField(blank=True, db_column='PreferredDays', max_length=200, null=True),
        ),
    ]
