# Generated by Django 6.0.6 on 2026-10-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_address_user_dob_user_gender_user_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermenu',
            name='approve_access',
            field=models.BooleanField(db_column='ApproveAccess', default=False),
        ),
        migrations.AddField(
            model_name='mastermenu',
            name='export_access',
            field=models.BooleanField(db_column='ExportAccess', default=False),
        ),
        migrations.AddField(
            model_name='mastersubmenu',
            name='approve_access',
            field=models.BooleanField(db_column='ApproveAccess', default=False),
        ),
        migrations.AddField(
            model_name='mastersubmenu',
            name='export_access',
            field=models.BooleanField(db_column='ExportAccess', default=False),
        ),
        migrations.AddField(
            model_name='roleaccess',
            name='approve_access',
            field=models.BooleanField(db_column='ApproveAccess', default=False),
        ),
        migrations.AddField(
            model_name='roleaccess',
            name='export_access',
            field=models.BooleanField(db_column='ExportAccess', default=False),
        ),
    ]
