# Generated by Django 6.1.2 on 2026-10-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mastermenu_approve_access_mastermenu_export_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermenu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, db_column='ParentMenuId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='users.mastermenu'),
        ),
    ]
