# Generated by Django 6.1.2 on 2026-10-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mastermenu_parent_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermenu',
            name='display_order',
            field=models.IntegerField(db_column='DisplayOrder', default=0),
        ),
        migrations.AddField(
            model_name='mastersubmenu',
            name='display_order',
            field=models.IntegerField(db_column='DisplayOrder', default=0),
        ),
        migrations.AddField(
            model_name='roleaccess',
            name='display_order',
            field=models.IntegerField(db_column='DisplayOrder', default=0),
        ),
    ]
