# Generated by Django 6.0.6 on 2026-09-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(db_column='EventId', primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_column='EventName', max_length=255)),
                ('event_date', models.DateTimeField(db_column='EventDate')),
                ('venue', models.CharField(db_column='Venue', max_length=500)),
                ('description', models.TextField(db_column='Description')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(db_column='NotificationId', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('message', models.TextField(db_column='Message')),
                ('sent_date', models.DateTimeField(db_column='SentDate')),
                ('is_read', models.BooleanField(db_column='IsRead', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('role', models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
    ]
