# Generated by Django 6.0.6 on 2026-10-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course_description_course_fee_amount_and_more'),
        ('events', '0001_initial'),
        ('users', '0004_usercertification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='role',
        ),
        migrations.AddField(
            model_name='event',
            name='target_batch',
            field=models.ForeignKey(blank=True, db_column='TargetBatchId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='UserId', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
