# Generated by Django 6.0.6 on 2026-10-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_notification_role_event_target_batch_and_more'),
        ('users', '0005_user_address_user_dob_user_gender_user_parent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('venue_id', models.AutoField(db_column='VenueId', primary_key=True, serialize=False)),
                ('venue_name', models.CharField(db_column='VenueName', max_length=200)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=500, null=True)),
            ],
            options={
                'db_table': 'EventVenue',
            },
        ),
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('event_id', models.AutoField(db_column='EventId', primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_column='EventName', max_length=200)),
                ('event_type', models.CharField(blank=True, db_column='EventType', max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, db_column='EventDate', null=True)),
                ('start_time', models.TimeField(blank=True, db_column='StartTime', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='EndTime', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('status', models.SmallIntegerField(db_column='Status', default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to='users.user')),
                ('venue', models.ForeignKey(blank=True, db_column='VenueId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventvenue')),
            ],
            options={
                'db_table': 'EventMaster',
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('event_attendance_id', models.AutoField(db_column='EventAttendanceId', primary_key=True, serialize=False)),
                ('attendance_status', models.SmallIntegerField(db_column='AttendanceStatus')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('event', models.ForeignKey(db_column='EventId', on_delete=django.db.models.deletion.CASCADE, to='events.eventmaster')),
            ],
            options={
                'db_table': 'EventAttendance',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('event_participant_id', models.AutoField(db_column='EventParticipantId', primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='RegistrationDate')),
                ('event', models.ForeignKey(db_column='EventId', on_delete=django.db.models.deletion.CASCADE, to='events.eventmaster')),
                ('role', models.ForeignKey(blank=True, db_column='RoleId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'EventParticipant',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
