# Generated by Django 6.0.6 on 2026-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventvenue_eventmaster_eventattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='contact_person',
            field=models.CharField(blank=True, db_column='ContactPerson', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='contact_phone',
            field=models.CharField(blank=True, db_column='ContactPhone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='max_participants',
            field=models.IntegerField(blank=True, db_column='MaxParticipants', null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='organizer',
            field=models.CharField(blank=True, db_column='Organizer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='registration_end_date',
            field=models.DateField(blank=True, db_column='RegEndDate', null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='registration_start_date',
            field=models.DateField(blank=True, db_column='RegStartDate', null=True),
        ),
    ]
