# Generated by Django 6.0.6 on 2026-09-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('fee_id', models.AutoField(db_column='FeeId', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(db_column='BalanceAmount', decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(db_column='DueDate')),
                ('payment_date', models.DateField(blank=True, db_column='PaymentDate', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('course', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Fees',
            },
        ),
    ]
