# Generated by Django 6.0.6 on 2026-10-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teacherattendance_studentattendance_and_more'),
        ('finance', '0002_invoice_transaction'),
        ('users', '0004_usercertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountMaster',
            fields=[
                ('discount_id', models.AutoField(db_column='DiscountId', primary_key=True, serialize=False)),
                ('discount_name', models.CharField(db_column='DiscountName', max_length=200)),
                ('discount_type', models.SmallIntegerField(db_column='DiscountType')),
                ('discount_value', models.DecimalField(db_column='DiscountValue', decimal_places=2, max_digits=18)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'DiscountMaster',
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('fee_payment_id', models.AutoField(db_column='FeePaymentId', primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(blank=True, db_column='ReceiptNo', max_length=50, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_column='PaymentDate')),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, max_digits=18)),
                ('payment_mode', models.SmallIntegerField(db_column='PaymentMode')),
                ('transaction_no', models.CharField(blank=True, db_column='TransactionNo', max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'FeePayment',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('fee_type_id', models.AutoField(db_column='FeeTypeId', primary_key=True, serialize=False)),
                ('fee_type_name', models.CharField(db_column='FeeTypeName', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'FeeType',
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('receipt_id', models.AutoField(db_column='ReceiptId', primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(db_column='ReceiptNo', max_length=50)),
                ('receipt_date', models.DateTimeField(auto_now_add=True, db_column='ReceiptDate')),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=18)),
                ('generated_by', models.IntegerField(blank=True, db_column='GeneratedBy', null=True)),
                ('fee_payment', models.ForeignKey(db_column='FeePaymentId', on_delete=django.db.models.deletion.CASCADE, to='finance.feepayment')),
                ('student', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'FeeReceipt',
            },
        ),
        migrations.CreateModel(
            name='FeeRefund',
            fields=[
                ('refund_id', models.AutoField(db_column='RefundId', primary_key=True, serialize=False)),
                ('refund_amount', models.DecimalField(db_column='RefundAmount', decimal_places=2, max_digits=18)),
                ('refund_date', models.DateTimeField(auto_now_add=True, db_column='RefundDate')),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=500, null=True)),
                ('approved_by', models.IntegerField(blank=True, db_column='ApprovedBy', null=True)),
                ('receipt', models.ForeignKey(db_column='ReceiptId', on_delete=django.db.models.deletion.CASCADE, to='finance.feereceipt')),
                ('student', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'FeeRefund',
            },
        ),
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('course_fee_id', models.AutoField(db_column='CourseFeeId', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('effective_from', models.DateField(blank=True, db_column='EffectiveFrom', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('course', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('fee_type', models.ForeignKey(db_column='FeeTypeId', on_delete=django.db.models.deletion.CASCADE, to='finance.feetype')),
            ],
            options={
                'db_table': 'CourseFee',
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('student_fee_id', models.AutoField(db_column='StudentFeeId', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(db_column='DiscountAmount', decimal_places=2, default=0, max_digits=18)),
                ('final_amount', models.DecimalField(db_column='FinalAmount', decimal_places=2, max_digits=18)),
                ('due_date', models.DateField(blank=True, db_column='DueDate', null=True)),
                ('status', models.SmallIntegerField(db_column='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('batch', models.ForeignKey(blank=True, db_column='BatchId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch')),
                ('course', models.ForeignKey(blank=True, db_column='CourseId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('student', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'StudentFee',
            },
        ),
        migrations.AddField(
            model_name='feepayment',
            name='student_fee',
            field=models.ForeignKey(db_column='StudentFeeId', on_delete=django.db.models.deletion.CASCADE, to='finance.studentfee'),
        ),
        migrations.CreateModel(
            name='StudentFeeInstallment',
            fields=[
                ('installment_id', models.AutoField(db_column='InstallmentId', primary_key=True, serialize=False)),
                ('installment_no', models.IntegerField(db_column='InstallmentNo')),
                ('due_date', models.DateField(db_column='DueDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('paid_amount', models.DecimalField(db_column='PaidAmount', decimal_places=2, default=0, max_digits=18)),
                ('status', models.SmallIntegerField(db_column='Status')),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('student_fee', models.ForeignKey(db_column='StudentFeeId', on_delete=django.db.models.deletion.CASCADE, to='finance.studentfee')),
            ],
            options={
                'db_table': 'StudentFeeInstallment',
            },
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
