# Generated by Django 6.0.6 on 2026-09-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(db_column='AttendanceId', primary_key=True, serialize=False)),
                ('attendance_name', models.CharField(db_column='AttendanceName', max_length=100)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('last_date', models.DateTimeField(auto_now=True, db_column='LastDate')),
                ('last_changed_by', models.IntegerField(blank=True, db_column='LastChangedBy', null=True)),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(db_column='CourseId', primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_column='CourseName', max_length=255)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(db_column='BatchId', primary_key=True, serialize=False)),
                ('batch_name', models.CharField(db_column='BatchName', max_length=255)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('teacher', models.ForeignKey(db_column='TeacherId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('course', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
            options={
                'db_table': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.AutoField(db_column='TimetableId', primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(db_column='DayOfWeek', max_length=50)),
                ('start_time', models.TimeField(db_column='StartTime')),
                ('end_time', models.TimeField(db_column='EndTime')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('batch', models.ForeignKey(db_column='BatchId', on_delete=django.db.models.deletion.CASCADE, to='academics.batch')),
                ('teacher', models.ForeignKey(db_column='TeacherId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Timetable',
            },
        ),
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('user_attendance_id', models.AutoField(db_column='UserAttendanceId', primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_column='AttendanceDate')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('attendance', models.ForeignKey(db_column='AttendanceId', on_delete=django.db.models.deletion.CASCADE, to='academics.attendance')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserAttendance',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('user_course_id', models.AutoField(db_column='UserCourseId', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('last_date', models.DateTimeField(auto_now=True, db_column='LastDate')),
                ('last_changed_by', models.IntegerField(blank=True, db_column='LastChangedBy', null=True)),
                ('course', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'UserCourse',
            },
        ),
    ]
