# Generated by Django 6.0.6 on 2026-10-06 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course_description_course_fee_amount_and_more'),
        ('users', '0004_usercertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('teacher_attendance_id', models.AutoField(db_column='TeacherAttendanceId', primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_column='AttendanceDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'TeacherAttendance',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('student_attendance_id', models.AutoField(db_column='StudentAttendanceId', primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_column='AttendanceDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('last_changed_date', models.DateTimeField(auto_now=True, db_column='LastChangedDate', null=True)),
                ('last_changed_by', models.IntegerField(blank=True, db_column='LastChangedBy', null=True)),
                ('batch', models.ForeignKey(blank=True, db_column='BatchId', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.batch')),
                ('course', models.ForeignKey(blank=True, db_column='CourseId', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
            options={
                'db_table': 'StudentAttendance',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceDetail',
            fields=[
                ('student_attendance_detail_id', models.AutoField(db_column='StudentAttendanceDetailId', primary_key=True, serialize=False)),
                ('attendance_status', models.SmallIntegerField(db_column='AttendanceStatus')),
                ('check_in_time', models.TimeField(blank=True, db_column='CheckInTime', null=True)),
                ('check_out_time', models.TimeField(blank=True, db_column='CheckOutTime', null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('student', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('student_attendance', models.ForeignKey(db_column='StudentAttendanceId', on_delete=django.db.models.deletion.CASCADE, to='academics.studentattendance')),
            ],
            options={
                'db_table': 'StudentAttendanceDetail',
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendanceDetail',
            fields=[
                ('teacher_attendance_detail_id', models.AutoField(db_column='TeacherAttendanceDetailId', primary_key=True, serialize=False)),
                ('attendance_status', models.SmallIntegerField(db_column='AttendanceStatus')),
                ('check_in_time', models.TimeField(blank=True, db_column='CheckInTime', null=True)),
                ('check_out_time', models.TimeField(blank=True, db_column='CheckOutTime', null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('teacher', models.ForeignKey(db_column='TeacherId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('teacher_attendance', models.ForeignKey(db_column='TeacherAttendanceId', on_delete=django.db.models.deletion.CASCADE, to='academics.teacherattendance')),
            ],
            options={
                'db_table': 'TeacherAttendanceDetail',
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
