# Generated by Django 6.0.6 on 2026-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teacherattendance_studentattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(blank=True, db_column='BatchCode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='capacity',
            field=models.IntegerField(blank=True, db_column='Capacity', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(blank=True, db_column='EndTime', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(blank=True, db_column='StartTime', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, db_column='Category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, db_column='CourseCode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.IntegerField(blank=True, db_column='DurationMonths', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_sessions',
            field=models.IntegerField(blank=True, db_column='TotalSessions', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(db_column='EndDate', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(db_column='StartDate', null=True),
        ),
    ]
