# Generated by Django 6.0.6 on 2026-10-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_batch_batch_code_batch_capacity_batch_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(blank=True, db_column='Days', max_length=200, null=True),
        ),
    ]
