# Generated by Django 6.0.6 on 2026-10-06 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_days'),
        ('users', '0005_user_address_user_dob_user_gender_user_parent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(db_column='EnrollmentId', primary_key=True, serialize=False)),
                ('joining_date', models.DateField(blank=True, db_column='JoiningDate', null=True)),
                ('status', models.SmallIntegerField(db_column='Status', default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('batch', models.ForeignKey(blank=True, db_column='BatchId', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.batch')),
                ('course', models.ForeignKey(db_column='CourseId', on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('student', models.ForeignKey(db_column='StudentId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'StudentEnrollment',
            },
        ),
    ]
