# Generated by Django 6.1.2 on 2026-10-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentenrollment'),
        ('users', '0008_mastermenu_display_order_mastersubmenu_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('leave_request_id', models.AutoField(db_column='LeaveRequestId', primary_key=True, serialize=False)),
                ('user_type', models.CharField(db_column='UserType', max_length=50)),
                ('from_date', models.DateField(db_column='FromDate')),
                ('to_date', models.DateField(db_column='ToDate')),
                ('no_of_days', models.IntegerField(db_column='NoOfDays')),
                ('request_type', models.CharField(db_column='RequestType', max_length=100)),
                ('applied_date', models.DateTimeField(auto_now_add=True, db_column='AppliedDate')),
                ('manager_approval_on', models.DateTimeField(blank=True, db_column='ManagerApprovalOn', null=True)),
                ('manager_approval_status', models.CharField(db_column='ManagerApprovalStatus', default='Pending', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('created_by', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'LeaveRequest',
            },
        ),
    ]
