# Generated by Django 6.1.2 on 2026-10-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='BatchId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch'),
        ),
    ]
