# Generated by Django 6.1.2 on 2026-10-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_leaverequest_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_hrs',
            field=models.DecimalField(blank=True, db_column='DurationHrs', decimal_places=2, max_digits=5, null=True),
        ),
    ]
